drop table if exists ITEM;
CREATE TABLE ITEM(
ITEMID NUMBERIC(11),
NAME CHAR(1024),
BUY_PRICE CHAR(100),
CURRENTLY CHAR(100),
FIRST_BID CHAR(100),
NUMBEROFBIDS NUMBERIC(11),
DESCRIPTION CHAR(10000),
STARTED CHAR(20),
ENDS CHAR(20),
CATEGORYNAME CHAR(1024) ,
PRIMARY KEY(ITEMID,CATEGORYNAME)
);
drop table if exists USER;
CREATE TABLE USER(
USERID CHAR(100),
RATING NUMERIC(11),
LOCATION CHAR(100),
COUNTRY CHAR(100),
PRIMARY KEY(USERID)
);
drop table if exists BIDDER;
CREATE TABLE BIDDER(
USERID CHAR(100),
RATING NUMERIC(11) NOT NULL,
PRIMARY KEY(USERID),
FOREIGN KEY (USERID) REFERENCES USER
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (RATING) REFERENCES USER
ON DELETE CASCADE
ON UPDATE CASCADE
);
drop table if exists SELLER;
CREATE TABLE SELLER(
USERID CHAR(100),
LOCATION CHAR(100) NOT NULL,
COUNTRY CHAR(100) NOT NULL,
PRIMARY KEY(USERID),
FOREIGN KEY (USERID) REFERENCES USER
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (LOCATION) REFERENCES USER
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (COUNTRY) REFERENCES USER
ON DELETE CASCADE
ON UPDATE CASCADE
);
drop table if exists SELL;
CREATE TABLE SELL(
ITEMID NUMERIC(11),
USERID CHAR(100),
CATEGORYNAME CHAR(1024),
PRIMARY KEY(ITEMID,CATEGORYNAME),
FOREIGN KEY (ITEMID) REFERENCES ITEM
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (CATEGORYNAME) REFERENCES ITEM
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (USERID) REFERENCES SELLER
ON DELETE CASCADE
ON UPDATE CASCADE
);
drop table if exists BIDS;
CREATE TABLE BIDS(
ITEMID NUMERIC(11),
TIME CHAR(20),
AMOUNT CHAR(20),
USERID CHAR(100) NOT NULL,
CATEGORYNAME CHAR(1024),
PRIMARY KEY(USERID,CATEGORYNAME,ITEMID),
FOREIGN KEY (ITEMID) REFERENCES ITEM
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (CATEGORYNAME) REFERENCES ITEM
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (USERID) REFERENCES BIDDER
ON DELETE CASCADE
ON UPDATE CASCADE
);


