-- Drop tables if they exist
DROP TABLE IF EXISTS BIDS;
DROP TABLE IF EXISTS SELL;
DROP TABLE IF EXISTS SELLER;
DROP TABLE IF EXISTS BIDDER;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS ITEM;

-- Create ITEM table
CREATE TABLE ITEM (
    ITEMID NUMERIC(11),
    NAME VARCHAR(1024),
    BUY_PRICE DECIMAL(10, 2),
    CURRENTLY DECIMAL(10, 2),
    FIRST_BID DECIMAL(10, 2),
    NUMBEROFBIDS NUMERIC(11),
    DESCRIPTION TEXT,
    STARTED DATETIME,
    ENDS DATETIME,
    CATEGORYNAME VARCHAR(1024),
    PRIMARY KEY (ITEMID, CATEGORYNAME)
);

-- Create USER table
CREATE TABLE USER (
    USERID VARCHAR(100),
    RATING NUMERIC(11),
    LOCATION VARCHAR(100),
    COUNTRY VARCHAR(100),
    PRIMARY KEY (USERID)
);

-- Create BIDDER table
CREATE TABLE BIDDER (
    USERID VARCHAR(100),
    RATING NUMERIC(11) NOT NULL,
    PRIMARY KEY (USERID),
    FOREIGN KEY (USERID) REFERENCES USER(USERID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- Create SELLER table
CREATE TABLE SELLER (
    USERID VARCHAR(100),
    LOCATION VARCHAR(100) NOT NULL,
    COUNTRY VARCHAR(100) NOT NULL,
    PRIMARY KEY (USERID),
    FOREIGN KEY (USERID) REFERENCES USER(USERID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- Create SELL table
CREATE TABLE SELL (
    ITEMID NUMERIC(11),
    USERID VARCHAR(100),
    CATEGORYNAME VARCHAR(1024),
    PRIMARY KEY (ITEMID, CATEGORYNAME),
    FOREIGN KEY (ITEMID) REFERENCES ITEM(ITEMID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (USERID) REFERENCES SELLER(USERID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- Create BIDS table
CREATE TABLE BIDS (
    ITEMID NUMERIC(11),
    TIME DATETIME,
    AMOUNT DECIMAL(10, 2),
    USERID VARCHAR(100) NOT NULL,
    CATEGORYNAME VARCHAR(1024),
    PRIMARY KEY (USERID, CATEGORYNAME, ITEMID),
    FOREIGN KEY (ITEMID) REFERENCES ITEM(ITEMID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (USERID) REFERENCES BIDDER(USERID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);



